import {useEffect,useRef,useState} from 'react';
import {WS_URL} from '../services/config'; import {getAssignedVehicleId,getDeviceKey,setAssignedVehicleId} from '../services/device';
type LivePosition={latitude:number;longitude:number;accuracy:number;speed:number|null;heading:number|null};
export function MobileGps(){
 const [status,setStatus]=useState('REQUESTING LOCATION'); const [backend,setBackend]=useState('CONNECTING'); const [pos,setPos]=useState<LivePosition|null>(null); const [vehicleId,setVehicleId]=useState(getAssignedVehicleId()||'ASSIGNING'); const wsRef=useRef<WebSocket|null>(null); const watchRef=useRef<number|undefined>(undefined); const retryRef=useRef<number|undefined>(undefined);
 useEffect(()=>()=>{wsRef.current?.close();if(watchRef.current!==undefined)navigator.geolocation.clearWatch(watchRef.current);if(retryRef.current)window.clearTimeout(retryRef.current)},[]);
 const start=()=>{setStatus('REQUESTING LOCATION');const deviceKey=getDeviceKey();let assigned:string|undefined=getAssignedVehicleId()||undefined;const connect=()=>{const ws=new WebSocket(WS_URL);wsRef.current=ws;ws.onopen=()=>{setBackend('CONNECTED');ws.send(JSON.stringify({type:'DEVICE_JOIN',device_key:deviceKey,vehicle_id:assigned}))};ws.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='device_ack'){const id=String(message.vehicle_id);assigned=id;setAssignedVehicleId(id);setVehicleId(id)}};ws.onerror=()=>ws.close();ws.onclose=()=>{setBackend('DISCONNECTED');retryRef.current=window.setTimeout(connect,1500)}};connect();if(watchRef.current===undefined)watchRef.current=navigator.geolocation.watchPosition(p=>{const next={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading};setPos(next);setStatus('ACTIVE');const ws=wsRef.current;if(ws?.readyState===WebSocket.OPEN&&assigned)ws.send(JSON.stringify({type:'LOCATION_UPDATE',device_key:deviceKey,vehicle_id:assigned,source:'BROWSER_GPS',latitude:next.latitude,longitude:next.longitude,accuracy_m:next.accuracy,speed_mps:next.speed,heading_deg:next.heading,timestamp:Date.now()/1000}))},()=>setStatus('LOCATION DENIED'),{enableHighAccuracy:true,maximumAge:1000,timeout:10000})};
 return <main className="mobile"><div className="mobile-card"><div className="eyebrow">SMART DRIVE · CONNECTED TRUCK</div><h1>{vehicleId}</h1><div className="mobile-status">● GPS {status}</div><p>Allow location access to broadcast this vehicle's live position.</p><button onClick={start}>{pos?'RECONNECT GPS':'ENABLE LIVE LOCATION'}</button>{pos?<div className="coords"><label>LATITUDE<b>{pos.latitude.toFixed(8)}</b></label><label>LONGITUDE<b>{pos.longitude.toFixed(8)}</b></label><label>ACCURACY<b>±{pos.accuracy.toFixed(0)} m</b></label><label>SPEED<b>{pos.speed===null?'—':`${(pos.speed*3.6).toFixed(1)} km/h`}</b></label><label>HEADING<b>{pos.heading===null?'—':`${pos.heading.toFixed(0)}°`}</b></label></div>:<div className="coords waiting"><span>GPS coordinates will appear after permission is granted.</span></div>}<div className="mobile-status">● BACKEND {backend}</div></div></main>;
}
