import {useCallback,useEffect,useRef,useState} from 'react';
import type {World} from '../types'; import {WS_URL} from '../services/config'; import {getAssignedVehicleId,getDeviceKey,getDeviceName,setAssignedVehicleId} from '../services/device';
const fallback:World={mode:'LIVE',host_vehicle:{vehicle_id:'HOST-001',role:'HOST',latitude:null,longitude:null,speed_mps:null,heading_deg:null,satellites:0,fix:false,accuracy_m:null,source:'BROWSER_GPS',location_source:'BROWSER_GPS'},vehicles:[],system_status:{system:'OFFLINE',host_gps:'WAITING',trucks_online:0,camera:'DISCONNECTED',imu:'DISCONNECTED',v2v:'DISCONNECTED'},scenario:null,demo_running:false,host_vehicle_id:null};
export interface GPSDebug{permission:string;watchActive:boolean;callbackReceived:boolean;latitude:number|null;longitude:number|null;accuracy:number|null;speed:number|null;heading:number|null;lastSentAt:number|null;lastWorldAt:number|null}
export function useWorld(requestedRole:'HOST'|'MEMBER'|null){
 const [world,setWorld]=useState<World>(fallback);const [connected,setConnected]=useState(false);const [vehicleId,setVehicleId]=useState(getAssignedVehicleId()||'ASSIGNING');const [role,setRole]=useState(requestedRole||'');const [roleError,setRoleError]=useState('');const [debug,setDebug]=useState<GPSDebug>({permission:'UNKNOWN',watchActive:false,callbackReceived:false,latitude:null,longitude:null,accuracy:null,speed:null,heading:null,lastSentAt:null,lastWorldAt:null});
 const wsRef=useRef<WebSocket|null>(null);const assignedRef=useRef<string|undefined>(getAssignedVehicleId()||undefined);const latestRef=useRef<Record<string,unknown>|undefined>(undefined);const watchRef=useRef<number|undefined>(undefined);const deviceKeyRef=useRef(getDeviceKey());
 const sendLatest=useCallback(()=>{const ws=wsRef.current;const assigned=assignedRef.current;const latest=latestRef.current;if(ws?.readyState===WebSocket.OPEN&&assigned&&latest){ws.send(JSON.stringify({type:'LOCATION_UPDATE',device_key:deviceKeyRef.current,vehicle_id:assigned,...latest}));console.info('LOCATION UPDATE SENT',assigned,latest.latitude,latest.longitude);setDebug(d=>({...d,lastSentAt:Date.now()}))}},[]);
 const startLocation=useCallback(()=>{if(watchRef.current!==undefined)return;if(!('geolocation' in navigator)){setDebug(d=>({...d,permission:'UNAVAILABLE'}));return}setDebug(d=>({...d,permission:'REQUESTING',watchActive:true}));watchRef.current=navigator.geolocation.watchPosition(p=>{const next={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,speed_mps:p.coords.speed,heading_deg:p.coords.heading,timestamp:Date.now()/1000};latestRef.current=next;setDebug(d=>({...d,permission:'GRANTED',watchActive:true,callbackReceived:true,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading}));console.info('GPS POSITION RECEIVED',assignedRef.current,next);sendLatest()},e=>{console.warn('GPS ERROR',e.code,e.message);setDebug(d=>({...d,permission:e.code===1?'DENIED':'ERROR',watchActive:false}))},{enableHighAccuracy:true,maximumAge:1000,timeout:10000})},[sendLatest]);
 useEffect(()=>{if(!requestedRole)return;let timer:number|undefined;let stopped=false;let delay=1000;const connect=()=>{if(stopped)return;const ws=new WebSocket(WS_URL);wsRef.current=ws;ws.onopen=()=>{delay=1000;setConnected(true);console.info('WEBSOCKET OPEN',WS_URL);ws.send(JSON.stringify({type:'DEVICE_JOIN',device_id:deviceKeyRef.current,device_key:deviceKeyRef.current,vehicle_id:assignedRef.current,role:requestedRole,device_name:getDeviceName(),browser:navigator.userAgent,platform:navigator.platform})) ;sendLatest()};ws.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='ping'){ws.send(JSON.stringify({type:'pong'}));return}if(message.type==='DEVICE_REGISTERED'){const id=String(message.vehicle_id);assignedRef.current=id;setAssignedVehicleId(id);setVehicleId(id);setRole(String(message.role));setRoleError('');console.info('DEVICE REGISTERED',id,message.role);sendLatest();return}if(message.type==='ROLE_REJECTED'){setRoleError(String(message.reason||'ROLE_REJECTED'));return}if(message.type==='world_state'||message.mode){setWorld(message);setDebug(d=>({...d,lastWorldAt:Date.now()}));console.info('WORLD STATE RECEIVED',message.vehicles?.length??0)}};ws.onclose=()=>{setConnected(false);timer=window.setTimeout(connect,delay);delay=Math.min(delay*2,30000)};ws.onerror=()=>ws.close()};connect();const heartbeat=window.setInterval(()=>{if(wsRef.current?.readyState===WebSocket.OPEN&&assignedRef.current)wsRef.current.send(JSON.stringify({type:'DEVICE_HEARTBEAT',device_key:deviceKeyRef.current,vehicle_id:assignedRef.current}))},3000);return()=>{stopped=true;if(timer)window.clearTimeout(timer);window.clearInterval(heartbeat);wsRef.current?.close()}},[requestedRole,sendLatest]);
 return {world,connected,vehicleId,role,roleError,debug,startLocation};
}
