import {useEffect,useState} from 'react';
import type {World} from '../types';
import {WS_URL} from '../services/config';
import {getAssignedVehicleId,getDeviceKey,setAssignedVehicleId} from '../services/device';
const fallback:World={mode:'LIVE',host_vehicle:{vehicle_id:'HOST-001',role:'HOST',latitude:null,longitude:null,speed_mps:null,heading_deg:null,satellites:0,fix:false,accuracy_m:null,source:'BROWSER_GPS',location_source:'BROWSER_GPS'},vehicles:[],system_status:{system:'OFFLINE',host_gps:'WAITING',trucks_online:0,camera:'DISCONNECTED',imu:'DISCONNECTED',v2v:'DISCONNECTED'},scenario:null,demo_running:false,host_vehicle_id:null};
export function useWorld(){
 const [world,setWorld]=useState<World>(fallback); const [connected,setConnected]=useState(false); const [vehicleId,setVehicleId]=useState(getAssignedVehicleId()||'ASSIGNING'); const [role,setRole]=useState('ASSIGNING');
 useEffect(()=>{const deviceKey=getDeviceKey();let assigned:string|undefined=getAssignedVehicleId()||undefined;let ws:WebSocket|undefined;let timer:number|undefined;let watch:number|undefined;let stopped=false;let delay=1000;let latest:Record<string,unknown>|undefined;
  const sendLatest=()=>{if(ws?.readyState===WebSocket.OPEN&&assigned&&latest)ws.send(JSON.stringify({type:'LOCATION_UPDATE',device_key:deviceKey,vehicle_id:assigned,...latest}))};
  const connect=()=>{if(stopped)return;ws=new WebSocket(WS_URL);ws.onopen=()=>{delay=1000;setConnected(true);ws?.send(JSON.stringify({type:'DEVICE_JOIN',device_key:deviceKey,vehicle_id:assigned}));sendLatest()};ws.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='ping'){ws?.send(JSON.stringify({type:'pong'}));return}if(message.type==='device_ack'){const id=String(message.vehicle_id);assigned=id;setAssignedVehicleId(id);setVehicleId(id);setRole(String(message.role));sendLatest();return}if(message.type==='world_state'||message.mode)setWorld(message)};ws.onclose=()=>{setConnected(false);timer=window.setTimeout(connect,delay);delay=Math.min(delay*2,30000)};ws.onerror=()=>ws?.close()};
  if('geolocation' in navigator)watch=navigator.geolocation.watchPosition(p=>{latest={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,speed_mps:p.coords.speed,heading_deg:p.coords.heading,timestamp:Date.now()/1000};sendLatest()},()=>{}, {enableHighAccuracy:true,maximumAge:1000,timeout:10000});connect();const heartbeat=window.setInterval(()=>{if(ws?.readyState===WebSocket.OPEN&&assigned)ws.send(JSON.stringify({type:'DEVICE_HEARTBEAT',device_key:deviceKey,vehicle_id:assigned}))},3000);return()=>{stopped=true;if(timer)window.clearTimeout(timer);window.clearInterval(heartbeat);if(watch!==undefined)navigator.geolocation.clearWatch(watch);ws?.close()};
 },[]); return {world,connected,vehicleId,role};
}
