import {useEffect,useState} from 'react';
import {Activity,CarFront,Map,Radio,Settings2,Volume2} from 'lucide-react';
import {useWorld} from './hooks/useWorld'; import {simulation,setMode} from './services/api'; import {SpatialView} from './components/SpatialView'; import {MapPanel} from './components/MapPanel'; import type {Risk} from './types'; import './styles.css';

export default function App(){
  const {world,connected,vehicleId,role}=useWorld(); const [scenario,setScenario]=useState('front_approach'); const [debug,setDebug]=useState(false);
  const topRisk:Risk=world.vehicles.some(v=>v.risk==='CRITICAL')?'CRITICAL':world.vehicles.some(v=>v.risk==='WARNING')?'WARNING':world.vehicles.some(v=>v.risk==='CAUTION')?'CAUTION':'SAFE'; const host=world.host_vehicle;
  useEffect(()=>{if(world.mode==='LIVE'&&(topRisk==='CRITICAL'||topRisk==='WARNING')){const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=topRisk==='CRITICAL'?880:520;o.connect(g);g.connect(c.destination);g.gain.value=.035;o.start();o.stop(c.currentTime+.12)}},[topRisk,world.mode]);
  const run=(action:'start'|'stop'|'reset')=>simulation(action,scenario);
  return <div className="app"><header><div className="brand"><div className="brand-mark"><CarFront size={19}/></div><div><b>SMART DRIVE</b><small>SIH26007 · SURROUNDING AWARENESS</small></div></div><div className="header-actions"><span className="live"><i/> {role==='HOST'?'HOST VEHICLE':role==='TRUCK'?'CONNECTED TRUCK':'ASSIGNING'} · {vehicleId} · {connected?'BACKEND CONNECTED':'RECONNECTING...'}</span><button className="icon" onClick={()=>setDebug(!debug)}><Settings2 size={18}/></button></div></header>
  <section className="alert-strip"><div><span className={`risk-chip ${topRisk.toLowerCase()}`}>{topRisk}</span><b>{world.mode==='LIVE'?(host.fix?'LIVE GPS MONITORING':'WAITING FOR GPS'):'DEMO MODE'}</b></div><span className="alert-detail">{world.vehicles.length+(role==='HOST'?1:0)} TRACKED VEHICLES · {world.mode}</span></section>
  <main><section className="hero-panel"><div className="panel-head"><div><span className="eyebrow">AWARENESS LAYER · {world.mode}</span><h1>Spatial vehicle view</h1></div><span className="heading"><Activity size={15}/> {host.heading_deg===null?'HEADING —':`HEADING ${Math.round(host.heading_deg)}°`}</span></div><SpatialView vehicles={world.vehicles}/><div className="vehicle-cards">{world.vehicles.length?world.vehicles.map(v=><div className="vehicle-card" key={v.vehicle_id}><span className="tiny-dot"/><div><b>{v.vehicle_id}</b><small>{v.role} · {v.location_source||v.source}</small></div><strong>{Math.round(v.distance_m)}m</strong><small>{v.status} · {v.accuracy_m===null?'accuracy —':`GPS ±${v.accuracy_m.toFixed(0)}m`}</small></div>):<div className="waiting-card">{world.mode==='LIVE'?'WAITING FOR CONNECTED TRUCKS':'NO SIMULATED VEHICLES'}</div>}</div></section>
  <section className="map-section"><div className="panel-head"><div><span className="eyebrow">MAP LAYER · AUTHORITATIVE WORLD STATE</span><h2>Navigation context</h2></div><span className="map-mode"><Map size={15}/> {world.mode}</span></div><MapPanel world={world}/></section>
  <section className="controls"><div><span className="eyebrow">OPERATING MODE</span><div className="control-row"><button onClick={()=>setMode('LIVE')}>LIVE MODE</button><select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="multiple">Multiple vehicles</option><option value="front_approach">Front approach</option><option value="left_approach">Left approach</option><option value="right_approach">Right approach</option><option value="behind">Vehicle behind</option></select><button className="secondary" onClick={()=>run('start')}>START DEMO</button><button className="secondary" onClick={()=>run('stop')}>EXIT DEMO</button></div></div><div className="sensor-row"><span>ROLE <b>{role}</b></span><span>HOST GPS <b>● {String(world.system_status.host_gps)}</b></span><span>TRUCKS <b>{String(world.system_status.trucks_online)}</b></span><span>CAMERA <b>● {String(world.system_status.camera)}</b></span></div></section>
  <section className="footer-stats"><div><span>SPEED</span><b>{host.speed_mps===null?'—':`${(host.speed_mps*3.6).toFixed(0)} `}<small>{host.speed_mps===null?'':'km/h'}</small></b></div><div><span>TRUCKS</span><b>{world.vehicles.length}</b></div><div><span><Radio size={13}/> GPS</span><b>{host.fix?'ACTIVE':'WAITING'}</b></div><div><span>RISK SCORE</span><b>{world.vehicles.length?Math.max(...world.vehicles.map(v=>v.risk_metrics.score)).toFixed(2):'—'}</b></div><div><span><Volume2 size={13}/> ALERTS</span><b>ARMED</b></div></section>
  {debug&&<aside className="debug"><b>DEVELOPER TELEMETRY</b><p>ROLE · {role} · {vehicleId}</p><p>GPS · {host.fix?'GRANTED':'UNAVAILABLE'} · SOURCE {host.location_source||'UNKNOWN'}</p><p>HOST · {host.latitude===null?'NO COORDINATES':`${host.latitude.toFixed(6)}, ${host.longitude!.toFixed(6)}`}</p><p>WEBSOCKET · {connected?'CONNECTED':'DISCONNECTED'}</p></aside>}</main></div>
}
